#!/bin/bash

# set up a list of dictionaries containing SDR data
# for import by Python scripts
# remove the first 6 and last lines of the file
listpath="../dyatlov/kiwisdr_com.js"

kiwidata="$(tail -n +7 "$listpath" | head -n -1)"
echo "dictlist = $kiwidata" > kiwisdr_stripped.py

# run scripts to use refined sdr data
#
# best sdrs according to SNR
python3 ./kiwisdr_best.py &
python3 ./hfgcs_updater.py &
python3 ./volmet_updater.py &
python3 ./canada_updater.py &
python3 ./ausnz_updater.py &
